name: CI

on: 
  push: 
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: | 
          cd frontend
          npm install
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        run: |
          cd api
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          cd api/tests
          python -m pytest

      
      